-- © 2026 Dastero Tech LLC — All rights reserved. See LICENSE.
-- SUPERSEDED — DO NOT RUN.
-- This migration created `profiles_select_self_or_admin`, which restricts a
-- non-admin to reading only their own profile row. That breaks owner-name
-- resolution across the shared board (owner tags / Pipeline owner+tree views).
-- The intended current policy is `profiles_select_authenticated` (read-all for
-- authenticated users) in sql/2026-06-23_profiles_read_all.sql. Apply that one.
